---
title: "README"
author: "Sanjay Somraj"
date: "June 16, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# DevelopingDataProducts_Assignment3
Repo for Coursera Developing Data Products Assignment 03

### Growth of tourism in India

Tourism in India is growing rapidly. The World Travel & Tourism Council calculated that tourism generated in year 2016 is US$220 billion.  

About 8.89 million foreign tourists arrived in India in 2016 compared to 8.027 million in 2015, recording a growth of 10.7%.  

The Travel & Tourism Competitiveness Report 2017 ranks India 40th out of 136 countries overall. The report ranks the price competitiveness of India's tourism sector 10th out of 136 countries. It mentions that India has quite good air transport (ranked 32nd), particularly given the country's stage of development, and reasonable ground transport infrastructure (ranked 29th).  

The country also scores high on natural and cultural resources (ranked 9th).[10] Some other aspects of its tourism infrastructure remain somewhat underdeveloped however.  

The World Tourism Organization reported that India's receipts from tourism during 2012 ranked 16th in the world, and 7th among Asian and Pacific countries.

### Foreign Tourist Arrival data
This assignments presents the **Foreign Tourist Arrival data** for the 12 year period from 2004 to 2015.  

The user can select a specific period, top 'n' ranking tourists and tourist origination continent/zone. 

This Shiny app has 5 Tab panels:
1)   **Tourist Data**: Provides tabular data of foreign tourist arrivals of the highest ranks (origination country), period selected and the geographical continent/zone of the tourist.
2)   **Data Visualization**: Display a bar graph of the foreign tourist arrivals for the selected criteria.
3)   **Data Summary**: Statistical summary of the foreign tourist arrivals for the period and geographical continent/zone of the tourist.
4)   **Help**: General help on how to use the Shiny app.
5)   **About**: Information about Tourism in India and references from where the data for this assignment has been sourced.

The source files for this Shiny app can be found in the **Github** repo - 

The Shiny app can be accessed at https://sanjaysomraj.shinyapps.io/assignment03/

### Reference
The data for this assignment has been sourced from -
1)   MARKET RESEARCH AND STATISTICS, Ministry of Tourism, Government of India.
*    http://tourism.gov.in/market-research-and-statistics
2)   Tourism in India from Wikipedia
*    https://en.wikipedia.org/wiki/Tourism_in_India
